### ISSUE TITLE
Support for config file

### ISSUE THREAD

**Issue by KonradIT** [KonradIT/mmt#24]
Stored as ~/.mmt.yaml` or passed via CLI arg.

**Comment by daktak** [comment]
Started on config file for import.go

Have to set defaults later I think, and required flags behave differently..

https://github.com/daktak/mmt/tree/config-file
```
import:
  camera: gopro
  output: /home/user/Videos
  input: 10.5.5.9
  connection: connect
```
